name: Create Dev Prerelease

on:
  push:
    branches:
      - master

jobs:
  prerelease:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Generate Changelog
        id: changelog
        run: |
          previous_tag=$(git describe --tags --abbrev=0 --match "dev-latest" 2>/dev/null || echo "")
          if [ -n "$previous_tag" ]; then
            range="$previous_tag..HEAD"
          else
            range=""
          fi
          changelog=$(git log --pretty=format:"- %s (%h)" $range)
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$changelog" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Merge .objects into objects.xml
        run: python scripts/merge_objects.py --data-path ModData/data

      - name: Create ZIP of ModData (excluding dot folders)
        run: |
          mkdir -p dist
          zip_name="SpiritOfFire-dev-latest.zip"

          cd ModData

          # Build a list of files NOT in dot-prefixed directories
          find . -type f ! -regex '\./\..*' ! -path './.*/*' > ../filelist.txt

          # Use zip with file list
          zip "../dist/$zip_name" -@ < ../filelist.txt

          cd ..


      - name: Create or Update Dev Prerelease
        uses: softprops/action-gh-release@v1
        with:
          tag_name: dev-latest
          name: Development Build
          body: ${{ steps.changelog.outputs.changelog }}
          prerelease: true
          files: dist/SpiritOfFire-dev-latest.zip
          token: ${{ secrets.GITHUB_TOKEN }}
